server:
  port: 9401
spring:
  profiles:
    active: dev
  application:
    name: micro-oauth2-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 18
    port: 6379
    host: 101.132.25.75
    password: vevor123456
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    path: /Users/qingshan/software/IdeaProjects/springcloud-learning/micro-oauth2/micro-oauth2-auth
  config: classpath:logback.xml