server:
  port: 9401
spring:
  profiles:
    active: dev
  application:
    name: micro-oauth2-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 15
    port: 6379
    host: 47.98.252.163
    password: GMadmins1318#
management:
  endpoints:
    web:
      exposure:
        include: "*"
